Added option to disable some alarms
rhythmictech/terraform-cis-cloudwatch-monitors pull request #6
Opened 2021-08-11 18:20 UTC by kmackowick

2021-08-12 14:12 UTC, sdickenson requested changes

2021-08-12 14:12 UTC, sdickenson commented on main.tf
> +  count               = var.core_alarms_only ? 0 : 1
`count` typically goes at the very top of the resource definition, per our engineering stands.

2021-08-12 15:16 UTC, kmackowick commented on main.tf
> +  count               = var.core_alarms_only ? 0 : 1
Fixed

2021-08-13 13:55 UTC, sdickenson approved these changes

2021-08-13 13:56 UTC, merged